version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 8081:80
    volumes:
      - ./:/var/www/project/
    networks:
      - symfony

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www/project/
    networks:
      - symfony

  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3311:3306
    networks:
      - symfony

networks:
  symfony: